name: Build and deploy API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./DecenaSoluciones.POS.API/DecenaSoluciones.POS.API.csproj
      
    - name: Build
      run: dotnet build ./DecenaSoluciones.POS.API/DecenaSoluciones.POS.API.csproj --configuration Release --no-restore

    - name: Dotnet publish
      run: dotnet publish ./DecenaSoluciones.POS.API/DecenaSoluciones.POS.API.csproj --configuration Release --no-restore --output ./publishApi --self-contained false -p:PublishTrimmed=false
    
    - name: App Settings
      uses: microsoft/variable-substitution@v1
      with:
        files: './publishApi/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.DEFAULT_CONNECTION_STRING }}
        AppSettings.TestingPeriod: ${{ secrets.TESTING_PERIOD }}
    
    - name: Upload to ftp      
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "./publishApi"
        dangerous-clean-slate: true
