name: Build API For Pull Request

on:
  pull_request:
    branches:
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./DecenaSoluciones.POS.API/DecenaSoluciones.POS.API.csproj
      
    - name: Build
      run: dotnet build ./DecenaSoluciones.POS.API/DecenaSoluciones.POS.API.csproj --configuration Release --no-restore
