name: Build and deploy WebApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./DecenaSoluciones.POS.WebApp/DecenaSoluciones.POS.WebApp.csproj
      
    - name: Build
      run: dotnet build ./DecenaSoluciones.POS.WebApp/DecenaSoluciones.POS.WebApp.csproj --configuration Release --no-restore

    - name: Dotnet publish
      run: dotnet publish ./DecenaSoluciones.POS.WebApp/DecenaSoluciones.POS.WebApp.csproj --configuration Release --no-restore --output ./publishWebApp --self-contained true -p:PublishTrimmed=false
    
    - name: App Settings
      uses: microsoft/variable-substitution@v1
      with:
        files: './publishWebApp/wwwroot/appsettings.json'
      env:
        ApiUrl: ${{ secrets.API_URL }}
    
    - name: Upload to ftp      
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "./publishWebApp"
        options: "--delete --asci"
